export enum reportCarTableHeaders {
    loop = 'Цикл',
    v = 'Vзад, кг',
    cem = 'Цемент зад, кг',
    cem2 = 'Цемент авт, кг',
    zap = 'Цем, %',
    zap2 = 'Зад зад',
    zap3 = 'Зап факт',
    zhhd = 'ЖХД зап',
    zhhd2= 'ЖХД авт кг',
    zhhd3 = 'ЖХД %',
    wat = 'ВОДА зад кг',
    wat2 = 'ВОДА авт кг',
    wat3 = 'ВОДА %',
}