export enum directoryModals {
    car = 'car',
    driver = 'driver',
    mixture = 'mixture',
    customer = 'customer',
    plants = 'plants',
    product = 'product',
    recComp = 'recComp',
    recFrost = 'recFrost',
    recMobility = 'recMobility',
    recStrength = 'recStrength',
    bsu = 'bsu',
    recWat = 'recWat',
    reportCurrentLoop = 'reportCurrentLoop',
    reportWeightManual = 'reportWeightManual',
    silCem = 'silCem',
    recipe = 'recipe',
    comp = 'comp',
    dispatcher = 'dispatcher',
    marka = 'marka',
    recComment = 'recComment',
    compType = 'compType',
    user = 'user',
    userEdit = 'userEdit',
}
export enum generalModals {
    ttnCreateModal ='ttnCreateModal',
    ttnEditModal = 'ttnEditModal',
    createRecipeNameModal = 'createRecipeNameModal',
    orderFilterModal = 'orderFilterModal',
}

export enum confirmModals {
    orderCreateConfirm = 'orderCreateConfirm',
    ttnCreateConfirm = 'ttnCreateConfirm',
    ttnEditConfirm = 'ttnEditConfirm',
    carCreateConfirm = 'carCreateConfirm',
    driverCreateConfirm = 'driverCreateConfirm',
    mixtureCreateConfirm = 'mixtureCreateConfirm',
    customerCreateConfirm = 'customerCreateConfirm',
    plantsCreateConfirm = 'plantsCreateConfirm',
    productCreateConfirm = 'productCreateConfirm',
    recCompCreateConfirm = 'recCompCreateConfirm',
    recFrostCreateConfirm = 'recFrostCreateConfirm',
    recMobilityCreateConfirm = 'recMobilityCreateConfirm',
    recStrengthCreateConfirm = 'recStrengthCreateConfirm',
    bsuCreateConfirm = 'bsuCreateConfirm',
    recWatCreateConfirm = 'recWatCreateConfirm',
    reportCurrentLoopCreateConfirm = 'reportCurrentLoopCreateConfirm',
    reportWeightManualCreateConfirm = 'reportWeightManualCreateConfirm',
    silCemCreateConfirm = 'silCemCreateConfirm',
    recipeCreateConfirm = 'recipeCreateConfirm',
    compCreateConfirm = 'compCreateConfirm',
    dispatcherCreateConfirm = 'dispatcherCreateConfirm',
    markaCreateConfirm = 'markaCreateConfirm',
    recCommentCreateConfirm = 'recCommentCreateConfirm',
    compTypeCreateConfirm = 'compTypeCreateConfirm',
    userCreateConfirm = 'userCreateConfirm',
    userEditConfirm = 'userEditConfirm',
}



