export const queries = {
    baseUrl: 'http://asaiot.net/dbu/api/',
    getCar: 'car.php',
    postCar: 'create/createCar.php',
    deleteCar: 'delete/deleteCar.php',
    editCar: 'edit/editCar.php',
    getDriver: 'driver.php',
    postDriver: 'create/createDriver.php',
    editDriver: 'edit/editDriver.php',

    getCustomer: 'customer.php',
    editCustomer: 'edit/editCustomer.php',

    graphAnalysis: 'graphAnalize.php',

    getOrders: 'order.php',

    postOrder: 'create/createOrder.php',
    getOrdersState: 'orderState.php',
    getOrdersStateEntities: 'stateMain.php?entityName=order',
    putOrdersStateEntities: 'edit/editOrder.php',
    getBsu: 'bsu.php',

    editPlants: 'edit/editPlants.php',
    getPlant: 'plants.php',

    getSilCem: 'silCem.php',
    getProduct: 'product.php',
    getReportCurrentLoop: 'reportCurrentLoop.php',
    getReportWeightManual: 'reportWeightManual.php',
    getMixture: 'mixture.php',
    getRecComp: 'recComp.php',
    getRecFrost: 'recFrost.php',
    getRecMobility: 'recMobility.php',
    editRecMobility: 'edit/editRecMobility.php',
    getRecStrength: 'recStrength.php',
    getRecWat: 'recWat.php',
    getTtn: 'ttn.php',
    postTtn: 'create/createTtn.php',
    getTtnStateEntities: 'stateMain.php?entityName=ttn',
    putTtnStateEntities: 'edit/editTtn.php',
    postPlant: 'create/createPlants.php',
    postBsu: 'create/createBsu.php',
    postSilCem: 'create/createSilCem.php',
    postProduct: 'create/createProduct.php',
    postReportCurrentLoop: 'create/createReportCurrentLoop.php',
    postReportWeightManual: 'create/createReportWeightManual.php',
    postMixture: 'create/createMixture.php',
    postRecComp: 'create/createRecComp.php',
    postRecFrost: 'create/createRecFrost.php',
    editRecFrost: 'edit/editRecFrost.php',
    postRecMobility: 'create/createRecMobility.php',
    postRecStrength: 'create/createRecStrength.php',
    postRecWat: 'create/createRecWat.php',
    editRecWat: 'edit/editRecWat.php',
    deleteBsu: 'delete/deleteBsu.php',
    editBsu: 'edit/editBsu.php',
    deleteCustomer: 'delete/deleteCustomer.php',
    deleteDriver: 'delete/deleteDriver.php',
    deleteMixture: 'delete/deleteMixture.php',
    editMixture: 'edit/editClassRecipe.php',
    deleteProduct: 'delete/deleteProduct.php',
    deleteRecComp: 'delete/deleteRecComp.php',
    deleteRecFrost: 'delete/deleteRecFrost.php',
    deleteRecMobility: 'delete/deleteRecMobility.php',
    deleteRecStrength: 'delete/deleteRecStrength.php',
    editRecStrength: 'edit/editRecStrength.php',
    deleteRecWat: 'delete/deleteRecWat.php',
    deleteReportCurrentLoop: 'delete/deleteReportCurrentLoop.php',
    deleteReportWeightManual: 'delete/deleteReportWeightManual.php',
    deleteRecipe: 'delete/deleteRecipe.php',
    postCustomer: 'create/createCustomer.php',
    deletePlant: 'delete/deletePlants.php',

    deleteSilCem: 'delete/deleteSilCem.php',
    editSilCem: 'edit/editSilCem.php',

    getRecipe: 'recipe.php',
    postRecipe: 'create/createRecipe.php',
    getMarka: 'recMarka.php',
    postMarka: 'create/createMarka.php',
    deleteMarka: 'delete/deleteRecMarka.php',
    editMarka: 'edit/editRecMarka.php',
    getComp: 'comp.php',
    editComp:'edit/editComp.php',
    deleteComp: 'delete/deleteComp.php',
    postComp: 'create/createComp.php',

    getDispatcher: 'dispatcher.php',
    postDispatcher: 'create/createDispatcher.php',
    deleteDispatcher: 'delete/deleteDispatcher.php',
    editDispatcher: 'edit/editDispatcher.php',

    getRecComment: 'recComment.php',
    postRecComment: 'create/createRecComment.php',
    editRecComment: 'edit/editRecComment.php',
    deleteRecComment: 'delete/deleteRecComment.php',
    editTtnFields: 'edit/editTtnFields.php',
    editOrderFields: 'edit/editOrderFields.php',
    getCurrentLoopCalculate: 'currentLoopCalculate.php',

    getClassRecipe: 'classRecipe.php',
    deleteClassRecipe: 'delete/deleteClassRecipe.php',
    postClassRecipe: 'create/createClassRecipe.php',

    getCompType: 'compType.php',
    postCompType: 'create/createCompType.php',
    deleteCompType: 'delete/deleteCompType.php',
    editCompType: 'edit/editCompType.php',

    loginUser: 'authorization/login.php',
    registerUser: 'authorization/register.php',
    getRoleName: 'role.php',
    deleteUser: 'delete/deleteUser.php',
    getUsers: 'users.php',
    editUser: 'edit/editUsers.php',

}